# coding: utf-8

"""
    Paragon Insights APIs

    API interface for PI application  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DatastoreSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group_name': 'str',
        'key': 'str',
        'value': 'object'
    }

    attribute_map = {
        'group_name': 'group-name',
        'key': 'key',
        'value': 'value'
    }

    def __init__(self, group_name=None, key=None, value=None):  # noqa: E501
        """DatastoreSchema - a model defined in Swagger"""  # noqa: E501

        self._group_name = None
        self._key = None
        self._value = None
        self.discriminator = None

        if group_name is not None:
            self.group_name = group_name
        if key is not None:
            self.key = key
        if value is not None:
            self.value = value

    @property
    def group_name(self):
        """Gets the group_name of this DatastoreSchema.  # noqa: E501

        group name  # noqa: E501

        :return: The group_name of this DatastoreSchema.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this DatastoreSchema.

        group name  # noqa: E501

        :param group_name: The group_name of this DatastoreSchema.  # noqa: E501
        :type: str
        """

        self._group_name = group_name

    @property
    def key(self):
        """Gets the key of this DatastoreSchema.  # noqa: E501

        key name for the group  # noqa: E501

        :return: The key of this DatastoreSchema.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this DatastoreSchema.

        key name for the group  # noqa: E501

        :param key: The key of this DatastoreSchema.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def value(self):
        """Gets the value of this DatastoreSchema.  # noqa: E501

        value for the key  # noqa: E501

        :return: The value of this DatastoreSchema.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DatastoreSchema.

        value for the key  # noqa: E501

        :param value: The value of this DatastoreSchema.  # noqa: E501
        :type: object
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatastoreSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatastoreSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
