# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: healthbot-hackers@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from jnpr.healthbot.swagger.models.device_schema_snmp_v2 import DeviceSchemaSnmpV2  # noqa: F401,E501


class DeviceSchemaSnmp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'port': 'int',
        'v2': 'DeviceSchemaSnmpV2'
    }

    attribute_map = {
        'port': 'port',
        'v2': 'v2'
    }

    def __init__(self, port=None, v2=None):  # noqa: E501
        """DeviceSchemaSnmp - a model defined in Swagger"""  # noqa: E501

        self._port = None
        self._v2 = None
        self.discriminator = None

        if port is not None:
            self.port = port
        if v2 is not None:
            self.v2 = v2

    @property
    def port(self):
        """Gets the port of this DeviceSchemaSnmp.  # noqa: E501

        Port on which SNMP requests need to be sent. Port 161 is used if not configured.  # noqa: E501

        :return: The port of this DeviceSchemaSnmp.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this DeviceSchemaSnmp.

        Port on which SNMP requests need to be sent. Port 161 is used if not configured.  # noqa: E501

        :param port: The port of this DeviceSchemaSnmp.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def v2(self):
        """Gets the v2 of this DeviceSchemaSnmp.  # noqa: E501


        :return: The v2 of this DeviceSchemaSnmp.  # noqa: E501
        :rtype: DeviceSchemaSnmpV2
        """
        return self._v2

    @v2.setter
    def v2(self, v2):
        """Sets the v2 of this DeviceSchemaSnmp.


        :param v2: The v2 of this DeviceSchemaSnmp.  # noqa: E501
        :type: DeviceSchemaSnmpV2
        """

        self._v2 = v2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceSchemaSnmp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
