# coding: utf-8

"""
    Paragon Insights APIs

    API interface for PI application  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TsdbPostBodyItemsOuterQueries(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fields': 'list[str]',
        'group_by': 'list[str]'
    }

    attribute_map = {
        'fields': 'fields',
        'group_by': 'groupBy'
    }

    def __init__(self, fields=None, group_by=None):  # noqa: E501
        """TsdbPostBodyItemsOuterQueries - a model defined in Swagger"""  # noqa: E501

        self._fields = None
        self._group_by = None
        self.discriminator = None

        if fields is not None:
            self.fields = fields
        if group_by is not None:
            self.group_by = group_by

    @property
    def fields(self):
        """Gets the fields of this TsdbPostBodyItemsOuterQueries.  # noqa: E501


        :return: The fields of this TsdbPostBodyItemsOuterQueries.  # noqa: E501
        :rtype: list[str]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this TsdbPostBodyItemsOuterQueries.


        :param fields: The fields of this TsdbPostBodyItemsOuterQueries.  # noqa: E501
        :type: list[str]
        """

        self._fields = fields

    @property
    def group_by(self):
        """Gets the group_by of this TsdbPostBodyItemsOuterQueries.  # noqa: E501


        :return: The group_by of this TsdbPostBodyItemsOuterQueries.  # noqa: E501
        :rtype: list[str]
        """
        return self._group_by

    @group_by.setter
    def group_by(self, group_by):
        """Sets the group_by of this TsdbPostBodyItemsOuterQueries.


        :param group_by: The group_by of this TsdbPostBodyItemsOuterQueries.  # noqa: E501
        :type: list[str]
        """

        self._group_by = group_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TsdbPostBodyItemsOuterQueries, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TsdbPostBodyItemsOuterQueries):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
