# coding: utf-8

"""
    Paragon Insights APIs

    API interface for PI application  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RuleSchemaThenRetry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'backoff': 'RuleSchemaThenRetryBackoff',
        'limit': 'int'
    }

    attribute_map = {
        'backoff': 'backoff',
        'limit': 'limit'
    }

    def __init__(self, backoff=None, limit=None):  # noqa: E501
        """RuleSchemaThenRetry - a model defined in Swagger"""  # noqa: E501

        self._backoff = None
        self._limit = None
        self.discriminator = None

        if backoff is not None:
            self.backoff = backoff
        if limit is not None:
            self.limit = limit

    @property
    def backoff(self):
        """Gets the backoff of this RuleSchemaThenRetry.  # noqa: E501


        :return: The backoff of this RuleSchemaThenRetry.  # noqa: E501
        :rtype: RuleSchemaThenRetryBackoff
        """
        return self._backoff

    @backoff.setter
    def backoff(self, backoff):
        """Sets the backoff of this RuleSchemaThenRetry.


        :param backoff: The backoff of this RuleSchemaThenRetry.  # noqa: E501
        :type: RuleSchemaThenRetryBackoff
        """

        self._backoff = backoff

    @property
    def limit(self):
        """Gets the limit of this RuleSchemaThenRetry.  # noqa: E501

        Maximum number of retry attempts  # noqa: E501

        :return: The limit of this RuleSchemaThenRetry.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this RuleSchemaThenRetry.

        Maximum number of retry attempts  # noqa: E501

        :param limit: The limit of this RuleSchemaThenRetry.  # noqa: E501
        :type: int
        """

        self._limit = limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RuleSchemaThenRetry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RuleSchemaThenRetry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
