# coding: utf-8

"""
    Paragon Insights APIs

    API interface for PI application  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pin_graphs_query import PinGraphsQuery  # noqa: E501
from swagger_client.rest import ApiException


class TestPinGraphsQuery(unittest.TestCase):
    """PinGraphsQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPinGraphsQuery(self):
        """Test PinGraphsQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pin_graphs_query.PinGraphsQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
