# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: healthbot-hackers@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.configuration_api import ConfigurationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.configuration_api.ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_device_group_unsaved_configuration(self):
        """Test case for check_device_group_unsaved_configuration

        Check if the un-committed configuration of the given device group is correct  # noqa: E501
        """
        pass

    def test_check_network_group_unsaved_configuration(self):
        """Test case for check_network_group_unsaved_configuration

        Check if the unsaved configuration of the given network group is correct.  # noqa: E501
        """
        pass

    def test_commit_unsaved_configuration(self):
        """Test case for commit_unsaved_configuration

        Commit unsaved configuration.  # noqa: E501
        """
        pass

    def test_create_iceberg_device_device_by_id(self):
        """Test case for create_iceberg_device_device_by_id

        Update or create a device.  # noqa: E501
        """
        pass

    def test_create_iceberg_device_group_device_group_by_id(self):
        """Test case for create_iceberg_device_group_device_group_by_id

        Update or create a device-group.  # noqa: E501
        """
        pass

    def test_create_iceberg_device_groups_device_groups_by_id(self):
        """Test case for create_iceberg_device_groups_device_groups_by_id

        Update or create multiple device-groups.  # noqa: E501
        """
        pass

    def test_create_iceberg_devices_devices_by_id(self):
        """Test case for create_iceberg_devices_devices_by_id

        Update or create multiple devices.  # noqa: E501
        """
        pass

    def test_create_iceberg_network_group_network_group_by_id(self):
        """Test case for create_iceberg_network_group_network_group_by_id

        Update or create a network-group.  # noqa: E501
        """
        pass

    def test_create_iceberg_network_groups_network_groups_by_id(self):
        """Test case for create_iceberg_network_groups_network_groups_by_id

        Update or create multiple network-groups.  # noqa: E501
        """
        pass

    def test_create_iceberg_notification_notification_by_id(self):
        """Test case for create_iceberg_notification_notification_by_id

        Update or create a notification  # noqa: E501
        """
        pass

    def test_create_iceberg_notifications_notifications_by_id(self):
        """Test case for create_iceberg_notifications_notifications_by_id

        Update or create multiple notifications.  # noqa: E501
        """
        pass

    def test_create_iceberg_playbook_playbook_by_id(self):
        """Test case for create_iceberg_playbook_playbook_by_id

        Update or create a playbook.  # noqa: E501
        """
        pass

    def test_create_iceberg_playbooks_playbooks_by_id(self):
        """Test case for create_iceberg_playbooks_playbooks_by_id

        Update or create multiple playbooks.  # noqa: E501
        """
        pass

    def test_create_iceberg_retention_policies_retention_policies_by_id(self):
        """Test case for create_iceberg_retention_policies_retention_policies_by_id

        Update or create multiple retention-policies.  # noqa: E501
        """
        pass

    def test_create_iceberg_retention_policy_retention_policy_by_id(self):
        """Test case for create_iceberg_retention_policy_retention_policy_by_id

        Update or create a retention-policy.  # noqa: E501
        """
        pass

    def test_create_iceberg_system_settings_destination_by_id(self):
        """Test case for create_iceberg_system_settings_destination_by_id

        Create destination by name  # noqa: E501
        """
        pass

    def test_create_iceberg_system_settings_destinations(self):
        """Test case for create_iceberg_system_settings_destinations

        Create destinations by name  # noqa: E501
        """
        pass

    def test_create_iceberg_system_settings_report_by_id(self):
        """Test case for create_iceberg_system_settings_report_by_id

        Create report by name  # noqa: E501
        """
        pass

    def test_create_iceberg_system_settings_reports(self):
        """Test case for create_iceberg_system_settings_reports

        Create reports by name  # noqa: E501
        """
        pass

    def test_create_iceberg_system_settings_scheduler_by_id(self):
        """Test case for create_iceberg_system_settings_scheduler_by_id

        Create scheduler by name  # noqa: E501
        """
        pass

    def test_create_iceberg_system_settings_schedulers(self):
        """Test case for create_iceberg_system_settings_schedulers

        Create schedulers by name  # noqa: E501
        """
        pass

    def test_create_iceberg_system_settings_system_settings_by_id(self):
        """Test case for create_iceberg_system_settings_system_settings_by_id

        Create system-settings  # noqa: E501
        """
        pass

    def test_create_iceberg_topic_rule_rule_by_id(self):
        """Test case for create_iceberg_topic_rule_rule_by_id

        Update or create a rule.  # noqa: E501
        """
        pass

    def test_create_iceberg_topic_topic_by_id(self):
        """Test case for create_iceberg_topic_topic_by_id

        Update or create a topic.  # noqa: E501
        """
        pass

    def test_create_iceberg_topics_topics_by_id(self):
        """Test case for create_iceberg_topics_topics_by_id

        Update or create multiple topics.  # noqa: E501
        """
        pass

    def test_delete_iceberg_device_device_by_id(self):
        """Test case for delete_iceberg_device_device_by_id

        Delete device.  # noqa: E501
        """
        pass

    def test_delete_iceberg_device_group_device_group_by_id(self):
        """Test case for delete_iceberg_device_group_device_group_by_id

        Delete device-group.  # noqa: E501
        """
        pass

    def test_delete_iceberg_device_groups_device_groups_by_id(self):
        """Test case for delete_iceberg_device_groups_device_groups_by_id

        Delete all device-groups.  # noqa: E501
        """
        pass

    def test_delete_iceberg_devices_devices_by_id(self):
        """Test case for delete_iceberg_devices_devices_by_id

        Delete all devices.  # noqa: E501
        """
        pass

    def test_delete_iceberg_network_group_network_group_by_id(self):
        """Test case for delete_iceberg_network_group_network_group_by_id

        Delete network-group.  # noqa: E501
        """
        pass

    def test_delete_iceberg_network_groups_network_groups_by_id(self):
        """Test case for delete_iceberg_network_groups_network_groups_by_id

        Delete all network-groups.  # noqa: E501
        """
        pass

    def test_delete_iceberg_notification_notification_by_id(self):
        """Test case for delete_iceberg_notification_notification_by_id

        Delete a notification.  # noqa: E501
        """
        pass

    def test_delete_iceberg_notifications_notifications_by_id(self):
        """Test case for delete_iceberg_notifications_notifications_by_id

        Delete all notifications.  # noqa: E501
        """
        pass

    def test_delete_iceberg_playbook_playbook_by_id(self):
        """Test case for delete_iceberg_playbook_playbook_by_id

        Delete a playbook.  # noqa: E501
        """
        pass

    def test_delete_iceberg_playbooks_playbooks_by_id(self):
        """Test case for delete_iceberg_playbooks_playbooks_by_id

        Delete all playbooks.  # noqa: E501
        """
        pass

    def test_delete_iceberg_retention_policies_retention_policies_by_id(self):
        """Test case for delete_iceberg_retention_policies_retention_policies_by_id

        Delete all retention-policies.  # noqa: E501
        """
        pass

    def test_delete_iceberg_retention_policy_retention_policy_by_id(self):
        """Test case for delete_iceberg_retention_policy_retention_policy_by_id

        Delete a retention-policy.  # noqa: E501
        """
        pass

    def test_delete_iceberg_system_settings_destination_by_id(self):
        """Test case for delete_iceberg_system_settings_destination_by_id

        Delete destination by name  # noqa: E501
        """
        pass

    def test_delete_iceberg_system_settings_destinations(self):
        """Test case for delete_iceberg_system_settings_destinations

        Delete destinations by name  # noqa: E501
        """
        pass

    def test_delete_iceberg_system_settings_report_by_id(self):
        """Test case for delete_iceberg_system_settings_report_by_id

        Delete report by name  # noqa: E501
        """
        pass

    def test_delete_iceberg_system_settings_reports(self):
        """Test case for delete_iceberg_system_settings_reports

        Delete reports by name  # noqa: E501
        """
        pass

    def test_delete_iceberg_system_settings_scheduler_by_id(self):
        """Test case for delete_iceberg_system_settings_scheduler_by_id

        Delete scheduler by name  # noqa: E501
        """
        pass

    def test_delete_iceberg_system_settings_schedulers(self):
        """Test case for delete_iceberg_system_settings_schedulers

        Delete schedulers by name  # noqa: E501
        """
        pass

    def test_delete_iceberg_system_settings_system_settings_by_id(self):
        """Test case for delete_iceberg_system_settings_system_settings_by_id

        Delete system-settings  # noqa: E501
        """
        pass

    def test_delete_iceberg_topic_rule_rule_by_id(self):
        """Test case for delete_iceberg_topic_rule_rule_by_id

        Delete a rule.  # noqa: E501
        """
        pass

    def test_delete_iceberg_topic_topic_by_id(self):
        """Test case for delete_iceberg_topic_topic_by_id

        Delete a topic.  # noqa: E501
        """
        pass

    def test_delete_iceberg_topics_topics_by_id(self):
        """Test case for delete_iceberg_topics_topics_by_id

        Delete all topics.  # noqa: E501
        """
        pass

    def test_retrieve_affected_groups(self):
        """Test case for retrieve_affected_groups

        Get all groups affected by un-committed configuration changes.  # noqa: E501
        """
        pass

    def test_retrieve_device_group_status(self):
        """Test case for retrieve_device_group_status

        Get device-group's status.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_device_device(self):
        """Test case for retrieve_iceberg_device_device

        List all device-ids.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_device_device_by_id(self):
        """Test case for retrieve_iceberg_device_device_by_id

        Get a device's configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_device_group_device_group(self):
        """Test case for retrieve_iceberg_device_group_device_group

        List all device-group names.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_device_group_device_group_by_id(self):
        """Test case for retrieve_iceberg_device_group_device_group_by_id

        Get device-group's configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_device_groups_device_groups(self):
        """Test case for retrieve_iceberg_device_groups_device_groups

        Get all device-groups' configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_devices_devices(self):
        """Test case for retrieve_iceberg_devices_devices

        Get all devices' configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_network_group_network_group(self):
        """Test case for retrieve_iceberg_network_group_network_group

        List all network-group names.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_network_group_network_group_by_id(self):
        """Test case for retrieve_iceberg_network_group_network_group_by_id

        Get network-group's configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_network_groups_network_groups(self):
        """Test case for retrieve_iceberg_network_groups_network_groups

        Get all network-groups' configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_notification_notification(self):
        """Test case for retrieve_iceberg_notification_notification

        List all notification-names.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_notification_notification_by_id(self):
        """Test case for retrieve_iceberg_notification_notification_by_id

        Get a notification's configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_notifications_notifications_by_id(self):
        """Test case for retrieve_iceberg_notifications_notifications_by_id

        Get all notifications' configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_playbook_playbook(self):
        """Test case for retrieve_iceberg_playbook_playbook

        List all playbook-names.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_playbook_playbook_by_id(self):
        """Test case for retrieve_iceberg_playbook_playbook_by_id

        Get a playbook's configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_playbooks_playbooks_by_id(self):
        """Test case for retrieve_iceberg_playbooks_playbooks_by_id

        Get all playbooks' configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_retention_policies_retention_policies_by_id(self):
        """Test case for retrieve_iceberg_retention_policies_retention_policies_by_id

        Get all retention-policies' configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_retention_policy_retention_policy(self):
        """Test case for retrieve_iceberg_retention_policy_retention_policy

        List all retention-policy-names.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_retention_policy_retention_policy_by_id(self):
        """Test case for retrieve_iceberg_retention_policy_retention_policy_by_id

        Get a retention-policy's configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_system_settings_destination_by_id(self):
        """Test case for retrieve_iceberg_system_settings_destination_by_id

        Retrieve destination by name  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_system_settings_destinations(self):
        """Test case for retrieve_iceberg_system_settings_destinations

        Retrieve destinations by name  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_system_settings_report_by_id(self):
        """Test case for retrieve_iceberg_system_settings_report_by_id

        Retrieve report by name  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_system_settings_reports(self):
        """Test case for retrieve_iceberg_system_settings_reports

        Retrieve reports by name  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_system_settings_scheduler_by_id(self):
        """Test case for retrieve_iceberg_system_settings_scheduler_by_id

        Retrieve scheduler by name  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_system_settings_schedulers(self):
        """Test case for retrieve_iceberg_system_settings_schedulers

        Retrieve schedulers by name  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_system_settings_system_settings(self):
        """Test case for retrieve_iceberg_system_settings_system_settings

        Retrieve system-settings  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_topic_rule_rule(self):
        """Test case for retrieve_iceberg_topic_rule_rule

        List all rule-names in a topic.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_topic_rule_rule_by_id(self):
        """Test case for retrieve_iceberg_topic_rule_rule_by_id

        Get a rule's configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_topic_topic(self):
        """Test case for retrieve_iceberg_topic_topic

        List all topic-names.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_topic_topic_by_id(self):
        """Test case for retrieve_iceberg_topic_topic_by_id

        Get a topic's configuration.  # noqa: E501
        """
        pass

    def test_retrieve_iceberg_topics_topics(self):
        """Test case for retrieve_iceberg_topics_topics

        Get all topics' configuration.  # noqa: E501
        """
        pass

    def test_retrieve_network_group_status(self):
        """Test case for retrieve_network_group_status

        Get network-group's status.  # noqa: E501
        """
        pass

    def test_rollback_unsaved_configuration(self):
        """Test case for rollback_unsaved_configuration

        Delete the un-committed configuration.  # noqa: E501
        """
        pass

    def test_update_iceberg_device_device_by_id(self):
        """Test case for update_iceberg_device_device_by_id

        Overwrite a device.  # noqa: E501
        """
        pass

    def test_update_iceberg_device_group_device_group_by_id(self):
        """Test case for update_iceberg_device_group_device_group_by_id

        Overwrite a device-group.  # noqa: E501
        """
        pass

    def test_update_iceberg_device_groups_device_groups_by_id(self):
        """Test case for update_iceberg_device_groups_device_groups_by_id

        Overwrite device-groups.  # noqa: E501
        """
        pass

    def test_update_iceberg_devices_devices_by_id(self):
        """Test case for update_iceberg_devices_devices_by_id

        Overwrite devices.  # noqa: E501
        """
        pass

    def test_update_iceberg_network_group_network_group_by_id(self):
        """Test case for update_iceberg_network_group_network_group_by_id

        Overwrite a network-group.  # noqa: E501
        """
        pass

    def test_update_iceberg_network_groups_network_groups_by_id(self):
        """Test case for update_iceberg_network_groups_network_groups_by_id

        Overwrite network-groups.  # noqa: E501
        """
        pass

    def test_update_iceberg_notification_notification_by_id(self):
        """Test case for update_iceberg_notification_notification_by_id

        Overwrite a notification.  # noqa: E501
        """
        pass

    def test_update_iceberg_notifications_notifications_by_id(self):
        """Test case for update_iceberg_notifications_notifications_by_id

        Overwrite notifications.  # noqa: E501
        """
        pass

    def test_update_iceberg_playbook_playbook_by_id(self):
        """Test case for update_iceberg_playbook_playbook_by_id

        Overwrite a playbook.  # noqa: E501
        """
        pass

    def test_update_iceberg_playbooks_playbooks_by_id(self):
        """Test case for update_iceberg_playbooks_playbooks_by_id

        Overwrite all playbooks.  # noqa: E501
        """
        pass

    def test_update_iceberg_retention_policies_retention_policies_id(self):
        """Test case for update_iceberg_retention_policies_retention_policies_id

        Overwrite all retention-policies.  # noqa: E501
        """
        pass

    def test_update_iceberg_retention_policy_retention_policy_by_id(self):
        """Test case for update_iceberg_retention_policy_retention_policy_by_id

        Overwrite a retention-policy.  # noqa: E501
        """
        pass

    def test_update_iceberg_system_settings_destination_by_id(self):
        """Test case for update_iceberg_system_settings_destination_by_id

        Update destination by name  # noqa: E501
        """
        pass

    def test_update_iceberg_system_settings_destinations(self):
        """Test case for update_iceberg_system_settings_destinations

        Update destinations by name  # noqa: E501
        """
        pass

    def test_update_iceberg_system_settings_report_by_id(self):
        """Test case for update_iceberg_system_settings_report_by_id

        Update report by name  # noqa: E501
        """
        pass

    def test_update_iceberg_system_settings_reports(self):
        """Test case for update_iceberg_system_settings_reports

        Update reports by name  # noqa: E501
        """
        pass

    def test_update_iceberg_system_settings_scheduler_by_id(self):
        """Test case for update_iceberg_system_settings_scheduler_by_id

        Update scheduler by name  # noqa: E501
        """
        pass

    def test_update_iceberg_system_settings_schedulers(self):
        """Test case for update_iceberg_system_settings_schedulers

        Update schedulers by name  # noqa: E501
        """
        pass

    def test_update_iceberg_system_settings_system_settings_by_id(self):
        """Test case for update_iceberg_system_settings_system_settings_by_id

        Update system-settings by ID  # noqa: E501
        """
        pass

    def test_update_iceberg_topic_rule_rule_by_id(self):
        """Test case for update_iceberg_topic_rule_rule_by_id

        Overwrite a rule.  # noqa: E501
        """
        pass

    def test_update_iceberg_topic_topic_by_id(self):
        """Test case for update_iceberg_topic_topic_by_id

        Overwrite a topic.  # noqa: E501
        """
        pass

    def test_update_iceberg_topics_topics_by_id(self):
        """Test case for update_iceberg_topics_topics_by_id

        Overwrite topics.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
