# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: healthbot-hackers@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.profile_schema_datasummarization_raw import ProfileSchemaDatasummarizationRaw  # noqa: E501
from swagger_client.rest import ApiException


class TestProfileSchemaDatasummarizationRaw(unittest.TestCase):
    """ProfileSchemaDatasummarizationRaw unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfileSchemaDatasummarizationRaw(self):
        """Test ProfileSchemaDatasummarizationRaw"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.profile_schema_datasummarization_raw.ProfileSchemaDatasummarizationRaw()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
