# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: healthbot-hackers@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.when_lhs_rhs_group import WhenLhsRhsGroup  # noqa: E501
from swagger_client.rest import ApiException


class TestWhenLhsRhsGroup(unittest.TestCase):
    """WhenLhsRhsGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWhenLhsRhsGroup(self):
        """Test WhenLhsRhsGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.when_lhs_rhs_group.WhenLhsRhsGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
