# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.topic_schema_source import TopicSchemaSource  # noqa: E501
from swagger_client.rest import ApiException


class TestTopicSchemaSource(unittest.TestCase):
    """TopicSchemaSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTopicSchemaSource(self):
        """Test TopicSchemaSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.topic_schema_source.TopicSchemaSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
