# coding: utf-8

"""
    Paragon Insights APIs

    API interface for PI application  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.snmpnotification_schema_snmpnotification_v3_usm import SnmpnotificationSchemaSnmpnotificationV3Usm  # noqa: E501
from swagger_client.rest import ApiException


class TestSnmpnotificationSchemaSnmpnotificationV3Usm(unittest.TestCase):
    """SnmpnotificationSchemaSnmpnotificationV3Usm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnmpnotificationSchemaSnmpnotificationV3Usm(self):
        """Test SnmpnotificationSchemaSnmpnotificationV3Usm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.snmpnotification_schema_snmpnotification_v3_usm.SnmpnotificationSchemaSnmpnotificationV3Usm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
