# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: healthbot-hackers@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rule_schema_formula_1 import RuleSchemaFormula1  # noqa: E501
from swagger_client.rest import ApiException


class TestRuleSchemaFormula1(unittest.TestCase):
    """RuleSchemaFormula1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuleSchemaFormula1(self):
        """Test RuleSchemaFormula1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rule_schema_formula_1.RuleSchemaFormula1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
