# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: healthbot-hackers@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.device_groups_schema import DeviceGroupsSchema  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceGroupsSchema(unittest.TestCase):
    """DeviceGroupsSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceGroupsSchema(self):
        """Test DeviceGroupsSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.device_groups_schema.DeviceGroupsSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
