# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.device_schema_snmp_v3_sourceid import DeviceSchemaSnmpV3Sourceid  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceSchemaSnmpV3Sourceid(unittest.TestCase):
    """DeviceSchemaSnmpV3Sourceid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceSchemaSnmpV3Sourceid(self):
        """Test DeviceSchemaSnmpV3Sourceid"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.device_schema_snmp_v3_sourceid.DeviceSchemaSnmpV3Sourceid()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
