# coding: utf-8

"""
    Healthbot APIs

    API interface for Healthbot application  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: healthbot-hackers@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.logs_api import LogsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.logs_api.LogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_logs_for_device_group(self):
        """Test case for retrieve_logs_for_device_group

        Logs for the given device-group.  # noqa: E501
        """
        pass

    def test_retrieve_logs_for_device_group_service(self):
        """Test case for retrieve_logs_for_device_group_service

        Get the logs for the given service running for the given device-group.  # noqa: E501
        """
        pass

    def test_retrieve_logs_for_network_group(self):
        """Test case for retrieve_logs_for_network_group

        Logs for the given network group.  # noqa: E501
        """
        pass

    def test_retrieve_logs_for_network_group_service(self):
        """Test case for retrieve_logs_for_network_group_service

        Get the logs for the given service running for the given network-group.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
